---
- name: build
  hosts: build
  become: yes

  tasks:
  - name: install default-jdk
    apt:
      name: default-jdk
      state: present
      update_cache: yes

  - name: install maven
    apt:
      name: maven
      state: present

  - name: install git
    apt:
      name: git
      state: present

  - name: git clone
    git:
      repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      dest: /opt/boxfuse-sample-java-war-hello
      clone: yes
      update: yes

  - name: mvn package
    shell: mvn package
    args:
      chdir: /opt/boxfuse-sample-java-war-hello

  - name: copy file from remote host to local
    fetch:
      src: /opt/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /opt

- name: prod
  hosts: prod
  become: yes

  tasks:
  - name: install tomcat9
    apt:
      name: tomcat9
      state: present
      update_cache: yes

  - name: copy file to webapp
    ansible.builtin.copy:
      src: /opt/51.250.65.144/opt/boxfuse-sample-java-war-hello/target/hello-1.0.war
      dest: /var/lib/tomcat9/webapps/